### ISSUE TITLE
One error when import extractor

### ISSUE THREAD

**Issue by Fabien-LAFAGE-Pro** [xTITUSMAXIMUSX/graylog-pfsense#3]
Hi,

I'm testing your extractor with :
- pfSense 2.7.2
- Graylog 6.0.4

All is working fine except for one error on import :
- log (Docker) : java.lang.IllegalStateException: Configured lookup table <port_map_tcp> doesn't exist

This extractor is not imported :
```
    {
      "title": "Service port lookup",
      "extractor_type": "lookup_table",
      "converters": [],
      "order": 0,
      "cursor_strategy": "copy",
      "source_field": "destination-port",
      "target_field": "service_port",
      "extractor_config": {
        "lookup_table_name": "port_map_tcp"
      },
      "condition_type": "none",
      "condition_value": ""
    }
```

Thanks in advance.

**Comment by xTITUSMAXIMUSX** [comment]
Yes, that is my fault. I added a lookup table to put a name to common port numbers. like 80 = HTTP and so on. I have removed that and updated the version that I am currently running on to 6.0.4. Let me know if you are able to import it now.

**Comment by Fabien-LAFAGE-Pro** [comment]
Hi,
Yes, no error now.
Thanks a lot !
Have a nice day.
